import apsw
from typing import Callable

def connection_wal(connection: apsw.Connection) -> None: ...
def connection_busy_timeout(connection: apsw.Connection, duration_ms: int = 100) -> None: ...
def connection_enable_foreign_keys(connection: apsw.Connection) -> None: ...
def connection_dqs(connection: apsw.Connection) -> None: ...
def library_logging() -> None: ...

recommended: tuple[Callable, ...]

def apply(which: tuple[Callable, ...]) -> None: ...
