
class Color:
    def __init__(self, r: int = 255, g: int = 255, b: int = 255, a: int = 255) -> None: ...

    @property
    def r(self) -> int: ...
    @r.setter
    def r(self, val: int) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, val: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, val: int) -> None: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, val: int) -> None: ...