def init(video: bool = True, audio: bool = False, timer: bool = False, joystick: bool = False, controller: bool = False, haptic: bool = False, sensor: bool = False, events: bool = True) -> None: ...
def quit() -> None: ...
