#!/usr/bin/env python3
"""
Entry point for initialising and starting the application.
Sets up the Python path and starts the main app.
"""


import logging.config
import sys
from pathlib import Path

# Add directories to the Python path for module imports
path_dirs: list[str] = ["aroma", "pylibs", "exlibs"]
for d in path_dirs:
    path: Path = Path(__file__).parent / d
    sys.path.insert(0, str(path))


from aroma import (  # pylint: disable=wrong-import-position # type: ignore # nopep8
    app, constants)


def init() -> None:
    """
    Initializes and starts the application.
    """
    logging.config.fileConfig(
        f"{constants.PATH_PREFIX}/aroma/config/logging.conf"
    )
    init: app.App = app.App()
    init.start()


if __name__ == "__main__":
    init()
