from ctypes import c_int

__all__ = [
    "SDL_ALPHA_OPAQUE",
    "SDL_ALPHA_TRANSPARENT",
    "SDL_PixelType",
    "SDL_PIXELTYPE_UNKNOWN",
    "SDL_PIXELTYPE_INDEX1",
    "SDL_PIXELTYPE_INDEX4",
    "SDL_PIXELTYPE_INDEX8",
    "SDL_PIXELTYPE_PACKED8",
    "SDL_PIXELTYPE_PACKED16",
    "SDL_PIXELTYPE_PACKED32",
    "SDL_PIXELTYPE_ARRAYU8",
    "SDL_PIXELTYPE_ARRAYU16",
    "SDL_PIXELTYPE_ARRAYU32",
    "SDL_PIXELTYPE_ARRAYF16",
    "SDL_PIXELTYPE_ARRAYF32",
    "SDL_BitmapOrder",
    "SDL_BITMAPORDER_NONE",
    "SDL_BITMAPORDER_4321",
    "SDL_BITMAPORDER_1234",
    "SDL_PackedOrder",
    "SDL_PACKEDORDER_NONE",
    "SDL_PACKEDORDER_XRGB",
    "SDL_PACKEDORDER_RGBX",
    "SDL_PACKEDORDER_ARGB",
    "SDL_PACKEDORDER_RGBA",
    "SDL_PACKEDORDER_XBGR",
    "SDL_PACKEDORDER_BGRX",
    "SDL_PACKEDORDER_ABGR",
    "SDL_PACKEDORDER_BGRA",
    "SDL_ArrayOrder",
    "SDL_ARRAYORDER_NONE",
    "SDL_ARRAYORDER_RGB",
    "SDL_ARRAYORDER_RGBA",
    "SDL_ARRAYORDER_ARGB",
    "SDL_ARRAYORDER_BGR",
    "SDL_ARRAYORDER_BGRA",
    "SDL_ARRAYORDER_ABGR",
    "SDL_PackedLayout",
    "SDL_PACKEDLAYOUT_NONE",
    "SDL_PACKEDLAYOUT_332",
    "SDL_PACKEDLAYOUT_4444",
    "SDL_PACKEDLAYOUT_1555",
    "SDL_PACKEDLAYOUT_5551",
    "SDL_PACKEDLAYOUT_565",
    "SDL_PACKEDLAYOUT_8888",
    "SDL_PACKEDLAYOUT_2101010",
    "SDL_PACKEDLAYOUT_1010102",
    "SDL_PixelFormatEnum",
    "SDL_PIXELFORMAT_UNKNOWN",
    "SDL_PIXELFORMAT_INDEX1LSB",
    "SDL_PIXELFORMAT_INDEX1MSB",
    "SDL_PIXELFORMAT_INDEX4LSB",
    "SDL_PIXELFORMAT_INDEX4MSB",
    "SDL_PIXELFORMAT_INDEX8",
    "SDL_PIXELFORMAT_RGB332",
    "SDL_PIXELFORMAT_XRGB4444",
    "SDL_PIXELFORMAT_RGB444",
    "SDL_PIXELFORMAT_XBGR4444",
    "SDL_PIXELFORMAT_BGR444",
    "SDL_PIXELFORMAT_XRGB1555",
    "SDL_PIXELFORMAT_RGB555",
    "SDL_PIXELFORMAT_XBGR1555",
    "SDL_PIXELFORMAT_BGR555",
    "SDL_PIXELFORMAT_ARGB4444",
    "SDL_PIXELFORMAT_RGBA4444",
    "SDL_PIXELFORMAT_ABGR4444",
    "SDL_PIXELFORMAT_BGRA4444",
    "SDL_PIXELFORMAT_ARGB1555",
    "SDL_PIXELFORMAT_RGBA5551",
    "SDL_PIXELFORMAT_ABGR1555",
    "SDL_PIXELFORMAT_BGRA5551",
    "SDL_PIXELFORMAT_RGB565",
    "SDL_PIXELFORMAT_BGR565",
    "SDL_PIXELFORMAT_RGB24",
    "SDL_PIXELFORMAT_BGR24",
    "SDL_PIXELFORMAT_XRGB8888",
    "SDL_PIXELFORMAT_RGB888",
    "SDL_PIXELFORMAT_RGBX8888",
    "SDL_PIXELFORMAT_XBGR8888",
    "SDL_PIXELFORMAT_BGR888",
    "SDL_PIXELFORMAT_BGRX8888",
    "SDL_PIXELFORMAT_ARGB8888",
    "SDL_PIXELFORMAT_RGBA8888",
    "SDL_PIXELFORMAT_ABGR8888",
    "SDL_PIXELFORMAT_BGRA8888",
    "SDL_PIXELFORMAT_ARGB2101010",
    "SDL_PIXELFORMAT_RGBA32",
    "SDL_PIXELFORMAT_ARGB32",
    "SDL_PIXELFORMAT_BGRA32",
    "SDL_PIXELFORMAT_ABGR32",
    "SDL_PIXELFORMAT_YV12",
    "SDL_PIXELFORMAT_IYUV",
    "SDL_PIXELFORMAT_YUY2",
    "SDL_PIXELFORMAT_UYVY",
    "SDL_PIXELFORMAT_YVYU",
    "SDL_PIXELFORMAT_NV12",
    "SDL_PIXELFORMAT_NV21",
    "SDL_PIXELFORMAT_EXTERNAL_OES",
    "NAME_MAP",
    "ALL_PIXELFORMATS",
]

SDL_ALPHA_OPAQUE: int
SDL_ALPHA_TRANSPARENT: int
SDL_PixelType = c_int
SDL_PIXELTYPE_UNKNOWN: int
SDL_PIXELTYPE_INDEX1: int
SDL_PIXELTYPE_INDEX4: int
SDL_PIXELTYPE_INDEX8: int
SDL_PIXELTYPE_PACKED8: int
SDL_PIXELTYPE_PACKED16: int
SDL_PIXELTYPE_PACKED32: int
SDL_PIXELTYPE_ARRAYU8: int
SDL_PIXELTYPE_ARRAYU16: int
SDL_PIXELTYPE_ARRAYU32: int
SDL_PIXELTYPE_ARRAYF16: int
SDL_PIXELTYPE_ARRAYF32: int
SDL_BitmapOrder = c_int
SDL_BITMAPORDER_NONE: int
SDL_BITMAPORDER_4321: int
SDL_BITMAPORDER_1234: int
SDL_PackedOrder = c_int
SDL_PACKEDORDER_NONE: int
SDL_PACKEDORDER_XRGB: int
SDL_PACKEDORDER_RGBX: int
SDL_PACKEDORDER_ARGB: int
SDL_PACKEDORDER_RGBA: int
SDL_PACKEDORDER_XBGR: int
SDL_PACKEDORDER_BGRX: int
SDL_PACKEDORDER_ABGR: int
SDL_PACKEDORDER_BGRA: int
SDL_ArrayOrder = c_int
SDL_ARRAYORDER_NONE: int
SDL_ARRAYORDER_RGB: int
SDL_ARRAYORDER_RGBA: int
SDL_ARRAYORDER_ARGB: int
SDL_ARRAYORDER_BGR: int
SDL_ARRAYORDER_BGRA: int
SDL_ARRAYORDER_ABGR: int
SDL_PackedLayout = c_int
SDL_PACKEDLAYOUT_NONE: int
SDL_PACKEDLAYOUT_332: int
SDL_PACKEDLAYOUT_4444: int
SDL_PACKEDLAYOUT_1555: int
SDL_PACKEDLAYOUT_5551: int
SDL_PACKEDLAYOUT_565: int
SDL_PACKEDLAYOUT_8888: int
SDL_PACKEDLAYOUT_2101010: int
SDL_PACKEDLAYOUT_1010102: int

SDL_PixelFormatEnum = c_int
SDL_PIXELFORMAT_UNKNOWN: int
SDL_PIXELFORMAT_INDEX1LSB: int
SDL_PIXELFORMAT_INDEX1MSB: int
SDL_PIXELFORMAT_INDEX4LSB: int
SDL_PIXELFORMAT_INDEX4MSB: int
SDL_PIXELFORMAT_INDEX8: int
SDL_PIXELFORMAT_RGB332: int
SDL_PIXELFORMAT_XRGB4444: int
SDL_PIXELFORMAT_RGB444 = SDL_PIXELFORMAT_XRGB4444
SDL_PIXELFORMAT_XBGR4444: int
SDL_PIXELFORMAT_BGR444 = SDL_PIXELFORMAT_XBGR4444
SDL_PIXELFORMAT_XRGB1555: int
SDL_PIXELFORMAT_RGB555 = SDL_PIXELFORMAT_XRGB1555
SDL_PIXELFORMAT_XBGR1555: int
SDL_PIXELFORMAT_BGR555 = SDL_PIXELFORMAT_XBGR1555
SDL_PIXELFORMAT_ARGB4444: int
SDL_PIXELFORMAT_RGBA4444: int
SDL_PIXELFORMAT_ABGR4444: int
SDL_PIXELFORMAT_BGRA4444: int
SDL_PIXELFORMAT_ARGB1555: int
SDL_PIXELFORMAT_RGBA5551: int
SDL_PIXELFORMAT_ABGR1555: int
SDL_PIXELFORMAT_BGRA5551: int
SDL_PIXELFORMAT_RGB565: int
SDL_PIXELFORMAT_BGR565: int
SDL_PIXELFORMAT_RGB24: int
SDL_PIXELFORMAT_BGR24: int
SDL_PIXELFORMAT_XRGB8888: int
SDL_PIXELFORMAT_RGB888 = SDL_PIXELFORMAT_XRGB8888
SDL_PIXELFORMAT_RGBX8888: int
SDL_PIXELFORMAT_XBGR8888: int
SDL_PIXELFORMAT_BGR888 = SDL_PIXELFORMAT_XBGR8888
SDL_PIXELFORMAT_BGRX8888: int
SDL_PIXELFORMAT_ARGB8888: int
SDL_PIXELFORMAT_RGBA8888: int
SDL_PIXELFORMAT_ABGR8888: int
SDL_PIXELFORMAT_BGRA8888: int
SDL_PIXELFORMAT_ARGB2101010: int
SDL_PIXELFORMAT_RGBA32 = SDL_PIXELFORMAT_RGBA8888
SDL_PIXELFORMAT_ARGB32 = SDL_PIXELFORMAT_ARGB8888
SDL_PIXELFORMAT_BGRA32 = SDL_PIXELFORMAT_BGRA8888
SDL_PIXELFORMAT_ABGR32 = SDL_PIXELFORMAT_ABGR8888
SDL_PIXELFORMAT_YV12: int
SDL_PIXELFORMAT_IYUV: int
SDL_PIXELFORMAT_YUY2: int
SDL_PIXELFORMAT_UYVY: int
SDL_PIXELFORMAT_YVYU: int
SDL_PIXELFORMAT_NV12: int
SDL_PIXELFORMAT_NV21: int
SDL_PIXELFORMAT_EXTERNAL_OES: int
NAME_MAP: int
ALL_PIXELFORMATS: int
