from ctypes import Structure, Union, c_int, c_long, c_uint, c_ulong, c_void_p

from _typeshed import Incomplete

from .stdinc import Uint32

SDL_SYSWM_TYPE = c_int
SDL_SYSWM_UNKNOWN: int
SDL_SYSWM_WINDOWS: int
SDL_SYSWM_X11: int
SDL_SYSWM_DIRECTFB: int
SDL_SYSWM_COCOA: int
SDL_SYSWM_UIKIT: int
SDL_SYSWM_WAYLAND: int
SDL_SYSWM_MIR: int
SDL_SYSWM_WINRT: int
SDL_SYSWM_ANDROID: int
SDL_SYSWM_VIVANTE: int
SDL_SYSWM_OS2: int
SDL_SYSWM_HAIKU: int
SDL_SYSWM_KMSDRM: int
SDL_SYSWM_RISCOS: int
HWND = c_void_p
HDC = c_void_p
HINSTANCE = c_void_p
UINT = c_uint
WPARAM = c_ulong
LPARAM = c_long

class _winmsg(Structure): ...
class _x11msg(Structure): ...
class _dfbmsg(Structure): ...
class _cocoamsg(Structure): ...
class _uikitmsg(Structure): ...
class _vivantemsg(Structure): ...
BOOL = c_int
ULONG = Uint32
MPARAM = Uint32

class _os2msg(Structure): ...
class _msg(Union): ...
class SDL_SysWMmsg(Structure): ...
class _wininfo(Structure): ...
class _winrtinfo(Structure): ...
class _x11info(Structure): ...
class _dfbinfo(Structure): ...
class _cocoainfo(Structure): ...
class _uikitinfo(Structure): ...
class _wl(Structure): ...
class _mir(Structure): ...
class _android(Structure): ...
class _os2(Structure): ...
class _vivante(Structure): ...
class _kmsdrm(Structure): ...
class _info(Union): ...
class SDL_SysWMinfo(Structure): ...

SDL_GetWindowWMInfo: Incomplete
