name: 'Bump Version'

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  bump-version:
    name: 'Bump Version on development-branch'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          ref: 'develop'
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Push commits
        run: |
          git push
