name: 'Bump Version - Master'

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  bump-version:
    permissions: write-all
    name: 'Bump Version on master-branch'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          ref: 'master'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: pip install commitizen

      - name: Prepare for commits
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: bump version
        run: cz bump --yes
        continue-on-error: true

      - name: Push
        run: |
          git push
          git push --tags
        continue-on-error: true

