name: 'Create Release'

on:
  push:
    tags:
      - "!*.a*"
      - "*"
  workflow_dispatch:

jobs:
  tag-release:
    permissions: write-all
    name: 'Generate a Release from Master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: 'master'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create Assets
        run: python generate_release.py
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: aroma.zip
