name: 'Master branch protection'

on:
  pull_request:
    branches:
      - 'master'

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != develop ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; 
          then
            echo "Error: Pull request must come from 'develop' or 'hotfix/' branch"
            exit 1
          fi
